'use client'; // App Router kullanıyorsan bu satır kalmalı

import React, { createContext, useContext, useState, useEffect } from 'react';

const defaultLocale = 'tr';

const localizedStrings = {
    tr: {
        'language': 'Dil',
        'turkish': 'Türkçe',
        'english': 'İngilizce',
        'german': 'Almanca',
        'balanceTracking': 'Bakiye Takip',
        'balance': 'Bakiye',
        'addBalance': 'Bakiye Ekle',
        'removeBalance': 'Bakiye Çıkar',
        'amount': 'Miktar',
        'description': 'Açıklama',
        'cancel': 'İptal',
        'add': 'Ekle',
        'remove': 'Çıkar',
        'history': 'Geçmiş',
        'invalidInput': 'Geçerli bir miktar ve açıklama girin',
        'belowZeroError': 'Bakiye sıfırın altına inemez!',
        'noUsersFound': 'Kayıtlı kullanıcı bulunamadı',
        'errorOccurred': 'Hata oluştu',
        'noTransactionHistory': 'İşlem geçmişi bulunamadı.', // Türkçe
        'months': [
            'January',
            'February',
            'March',
            'April',
            'May',
            'June',
            'July',
            'August',
            'September',
            'October',
            'November',
            'December',
        ],
        'listings': 'İlanlar',
        'profile': 'Profil',
        'about': 'Hakkımızda',
        'barter': 'Barter Sistemi',
        'contact': 'İletişim',
        'logout': 'Çıkış Yap',
        'deleteAccount': 'Hesabımı Sil',
        'barterSystem': 'Barter Sistemi',
        'aboutUs': 'Hakkımızda',
        'about1':
            "ULUSAL Barter A.Ş. dünyada yaygın olarak kullanılan barter sisteminin, ülkemizin ticari faaliyetlerine yeni bir soluk getirmesi amacıyla kurulmuştur.",
        'about2':
            "Güçlü sermaye ve akılcı ticaret anlayışıyla, ekonomiğe katkısıyla kurumsal yapısının yanı sıra, profesyonel ekibi ile işini sahiplenen, sorunları çözme konusunda yaratıcılığını kullanan, akılcı çözümler üreten, ULUSAL Barter A.Ş. gelişmekte olan sektörün en güçlü temsilcisidir.",
        'about3':
            "Her yıl başarısını katlayarak arttıran ULUSAL Barter A.Ş. ülkenin önde gelen büyük holdingleri ile birçok ortak projede yer almış; hizmet politikası ile yer almış olduğu işlerden olumlu referanslar almıştır. Kazandığı olumlu referansların gücü ile portföyünü zenginleştiren ULUSAL Barter A.Ş. 5000 aşkın üye sayısına ulaşmıştır.",
        'about4':
            "Gün geçtikçe artmaya devam eden üye sayısının ve stratejik ortaklarının desteğiyle elde ettiği başarıları, ülkemizde gelişmekte olan barter sektörünün, yenilikçi, vizyoner ve kazançlı bir ticaret sistemi olarak tanınmasına katkıda bulunmaktadır.",
        'about5': "Katma değerli dış Ticaret projeleri geliştirirken;",
        'about6':
            "✓ ULUSAL Barter A.Ş. misyon, vizyon ve stratejisi ile hareket ederek, Ram iç ve Dış Ticaret olarak her türlü dışve iç ticaret operasyonunu ilgili tarafların ihtiyaç ve beklentilerini karşılayarak yapmayı,",
        'about7':
            "✓ Müşteri odaklı stratejisi ile en iyi hizmeti ve kusursuz hizmet sunmayı hedeflerken; iş ahlakı ve güvenilir duruşundan ödün vermemeyi,",
        'about8':
            "✓ 26 yıllık dış ve iç ticaret sektör tecrübesi, bilgi birikimi ve uzman ekibi ile sektöre öncü olmayı ve sektör standartları belirleyecek adımlar atarak gelişmeyi,",
        'about9':
            "✓ Ülke ekonomisine katkı sağlayacak ihracat faaliyetlerinde, kurumlara sağlayacağı finansal hizmetler ile en verimli ve optimum çözümler sunmayı,",
        'about10':
            "✓ Kusursuz hizmet misyonunu ile çalışanlarını ve etkileşim içinde olduğu ilgili taraflarını da kalite yolculuğunda birlikte yanında taşımayı ve sürekli geliştirmeyi,",
        'about11':
            "✓ Ulusal ve/veya uluslararası mevzuatlara uyum yükümlülüklerini yerine getirirken; çevreci yaklaşımlar ve sosyal sorumluluk projelerine de imza atarak ilgili tarafları ve çalışanlarının bilinç seviyesini artırmayı,",
        'about12':
            "✓ Teknolojik gelişmeleri takip ederek, inovatif yaklaşımlar ile operasyon ve hizmet kalitesini sürekli dijitalleştirmeyi,",
        'about13':
            "✓ Zor olanı başarmak ve hedeflerine ulaşmak için tüm bu faaliyetleri yürütürken bilgi birikimi ve sektör deneyimlerini kalite yönetim sistemi ile kurumsal hafızaya alarak, gelecek nesillere aktarmayı ve sistemi sürekli geliştirerek sürdürmeyi taahhüt eder.",
        'about14': "Misyonumuz ve Değerlerimiz",
        'about15':
            "Ülkemizin ticaret ve yatırımlar açısından çekim merkezi ve yaşam kalitesini sürekli artıran bir ülke haline getirmek, kaynakları etkin bir şekilde kullanarak geliştirdiği yenilikçi ve özgün projeler ile üyelerinin ticari faaliyetlerini kolaylaştırmak, iş dünyası ve topluma sürdürülebilir hizmetler sunmak.",
        'about16': "Geleceğe Yönelik Vizyonumuz",
        'about17':
            "Sürdürülebilir kalkınma amaçları doğrultusunda üyelerinin sektörel gelişim ve dönüşüm süreçlerine rehberlik eden, paydaşlarıyla birlikte değer yaratan, yaşam, ticaret ve yatırımda ülkemizin rol model Barter şirketi olmak.",
        'about18': "Yönetim Kurulu Başkanı",
        'about19': "Yönetim Kurulu Başkan Vekili",
        'about20': "Yönetim Kurulu Üyesi",
        'about21': "Pazarlama Koordinatörü",
        'about22': "Medya Tanıtım Koordinatörü",
        'about23': "Bilgi İşlem Koordinatörü",
        'about24': "Müşteri Koordinatörü",
        'about25': "Hukuk Koordinatörü",
        'about26': "Muhasebe Koordinatörü",
        'about27': "Emlak Koordinatörü",
        'about28': "Müşteri Temsilcisi",
        'about29': "Yönetim Kurulu",
        'about30': "Kuruluş Amacı",
        'about31': "Kurumsal Yapı ve Güçlü Kadro",
        'about32': "Başarı ve Referanslar",
        'about33': "Sektöre Katkı",
        'about34': "Faaliyet İlkeleri ve Hedefler",
        "about35": "Genel Bilgi",
        "about36": "Misyonumuz",
        "about37": "Vizyonumuz",
        'contactSubtitle': 'Bizimle iletişime geçmekten çekinmeyin.',
        'contactInfo': 'İletişim Bilgileri',
        'email': 'E-Mail',
        'phone': 'Telefon',
        'address': 'Adres',
        'register': 'Kayıt Ol',
        'firstName': 'Ad',
        'lastName': 'Soyad',
        'password': 'Şifre',
        'genericError': 'Bir hata oluştu.',
        'login': 'Giriş Yap',
        'forgotPassword': 'Şifremi Unuttum',
        'loginFailed': 'Giriş başarısız. Bilgilerinizi kontrol edin.',
        'userNotFound': 'Kullanıcı bulunamadı veya hesabınız silinmiş.',
        'notApproved': 'Hesabınız henüz yönetici tarafından onaylanmadı.',
        'userDataNotFound': 'Kullanıcı bilgileri bulunamadı.',
        'openMenu': 'Menüyü Aç',
        'myProfile': 'Profilim',
        'save': 'Kaydet',
        'edit': 'Düzenle',
        'updated': 'Bilgiler güncellendi',
        'emailLabel': 'E-posta adresiniz',
        'sendResetLink': 'Şifre Sıfırlama Bağlantısı Gönder',
        'sending': 'Gönderiliyor...',
        'goBack': 'Geri Dön',
        'resetLinkSent':
            'Şifre sıfırlama bağlantısı e-posta adresinize gönderildi.',
        'resetError': 'Bir hata oluştu. Lütfen e-posta adresinizi kontrol edin.',
        'offers': 'Teklifler',
        'offeredBy': 'Teklif veren',
        'noOffersYet': 'Henüz teklif yok',
        'unknownUser': 'Bilinmeyen',
        addProduct: "Ürün Ekle",
        productName: "Ürün Adı",
        price: "Fiyat",
        selectMainImage: "Ana Görsel Seç",
        addExtraImages: "Ek Görsel Ekle",
        addVideo: "Video Ekle",
        addDesc: "Açıklama Ekle",
        removeDesc: "Açıklamayı Sil",
        saveProduct: "Ürünü Kaydet",
        fillRequiredFields: "Lütfen ürün ismi, fiyat ve ana görsel ekleyin.",
        productSaved: "Ürün başarıyla kaydedildi.",
        productNotFound: "Düzenlenecek ürün bulunamadı.",
        productFetchError: "Ürün getirilirken hata",
        userNotFound: "Kullanıcı bilgisi alınamadı.",
        'favoriteAdded': 'Favorilere eklendi',
        'favoriteRemoved': 'Favorilerden çıkarıldı',
        'offerExists': 'Teklif zaten mevcut',
        'productSold': 'Satıldı',
        'makeOffer': 'Teklif Ver',
        'withdrawOffer': 'Teklifi Geri Çek',
        'addFavorite': 'Favorilere Ekle',
        'removeFavorite': 'Favorilerden Çıkar',
        'invalidAmount': 'Geçerli bir miktar girin',
        'successfull': 'Teklif başarıyla gönderildi',
        'withdrawnOffer': 'Teklifi Geri Çekildi',
        'markAsSold': 'Satıldı İşaretle',
        'unMarkSold': 'İşareti Kaldır',
        'confirmMarkAsSold':
            'Bu ürünü gerçekten satıldı olarak işaretlemek istiyor musunuz?',
        'confirmRemoveSoldMark':
            'Bu ürünün satıldı işaretini kaldırmak istiyor musunuz?',
        'yes': 'Evet',
        'deleteProduct': 'Ürünü Sil',
        'confirmDeleteProduct': 'Bu ürünü silmek istediğinize emin misiniz?',
        'delete': 'Sil',
        'productDetails': 'Ürün Detayları',
        'listingNumber': 'İlan Numarası: ',
        'loginToSeePrice': 'Fiyatı görmek için giriş yapın',
        'otherMedia': 'Diğer Medya',
        'searchLocation': 'Konum Ara',
        'hintLocation': 'Şehir, ilçe...',
        'type': 'Tür',
        'status': 'Durum',
        'all': 'Tümü',
        'sold': 'Satılanlar',
        'unsold': 'Satılmayanlar',
        'loadingContent': 'İçerik Yükleniyor...',
        'welcomeUser': 'Hoşgeldiniz',
        'productCount': 'ürün listeleniyor',
        'requests': 'İstekler',
        'filter': 'Filtre',
        'accountHistory': 'Hesap Geçmişi',
        'favorites': 'Favoriler',
        'noFavoritesFound': 'Favorilere eklenmiş ilan bulunamadı.',
        'close': 'Kapat',
        'myFavoriteAds': 'Favori İlanlarım',
        'ad': 'İlan',
        'myFavorites': 'Favorilerim',
        'noProductsFound': 'Hiç ürün bulunamadı.',
        'unnamedProduct': 'Ürün İsimsiz',
        'detail': 'Detay',
        'swapCompleted': 'TAKAS GERÇEKLEŞTİRİLMİŞTİR',
        'pinned': 'Üste sabitlendi',
        'unpinned': 'Sıralamaya geri alındı',
        'pin': 'Sabitle',
        'unpin': 'Kaldır',
        'noPendingUsers': 'Onay bekleyen kullanıcı yok.',
        'pendingUsers': 'Onay Bekleyen Kullanıcılar',
        'productTypes': [
            "Arsa", "Arazi", "Otel", "Hizmet", "Çiftlik",
            "Daire", "Villa", "Santral", "Restaurant", "Bahçe",
            "Tarla", "Parsel", "Tesis", "Zeytinlik", "Fabrika",
            "Beyaz Eşya", "Ofis", "Ev", "Malikane", "Tatil Köyü",
            "Taksi", "Tekstil", "Peyzaj", "Sera", "Estetik",
        ],
        "navbar.home": "Ana Sayfa",
        "navbar.about": "Hakkımızda",
        "navbar.barter": "Barter Sistemi",
        "navbar.products": "Ürün ve Hizmetler",
        "navbar.contact": "İletişim",
        "navbar.joinNow": "Hemen Üye Ol",
        contactPageTitle: "İLETİŞİM",
        contactPageSubtitle: "Bizimle iletişime geçmekten çekinmeyin.",
        contactInfoTitle: "İletişim Bilgileri",
        contactEmailLabel: "E-Posta",
        contactPhoneLabel: "Telefon",
        contactAddressLabel: "Adres",
        contactAddress: "Mansuroğlu Mah. 283/1 Sk. No:2 GSK Plaza K:1 D:201 Bayraklı/İzmir",
        contactFormTitle: "Mesaj Gönderin",
        contactFormName: "Ad Soyad",
        contactFormEmail: "E-posta",
        contactFormPhone: "Telefon",
        contactFormMessage: "Mesajınız",
        contactFormSubmit: "Mesaj Gönder",
        contactFormSuccess: "Mesajınız başarıyla gönderildi!",
        contactFormError: "Bir hata oluştu, lütfen tekrar deneyin.",
        registerTitle: "Kayıt Ol",
        registerPlaceholderFirstName: "Ad",
        registerPlaceholderLastName: "Soyad",
        registerPlaceholderPhone: "Telefon",
        registerPlaceholderAddress: "Adres",
        registerPlaceholderEmail: "E-Posta",
        registerPlaceholderPassword: "Şifre",
        registerErrorApproval: "Hesabınız yönetici onayı bekliyor.",
        registerErrorGeneral: "Kayıt başarısız. Lütfen bilgilerinizi kontrol edin.",
        registerButton: "Kayıt Ol",
        registerWarning: "Uyarı!",
        forgotTitle: "Şifremi Unuttum",
        forgotPlaceholderEmail: "E-posta adresiniz",
        forgotSending: "Gönderiliyor...",
        forgotButton: "Şifre Sıfırlama Bağlantısı Gönder",
        forgotError: "Bir hata oluştu. Lütfen mail adresinizi kontrol edin.",
        forgotSuccess: "Şifre sıfırlama bağlantısı mail adresinize gönderildi. Lütfen mailinizi kontrol edin.",
        loginTitle: "Giriş Yap",
        loginEmail: "E-posta",
        loginPassword: "Şifre",
        loginErrorApprove: "Hesabınız henüz onaylanmadı. Lütfen yönetici onayını bekleyin.",
        loginErrorNotFound: "Kullanıcı bilgileri bulunamadı.",
        loginErrorFailed: "Giriş başarısız. Lütfen bilgilerinizi kontrol edin.",
        loginButton: "Giriş Yap",
        loginRegister: "Kayıt Ol",
        loginForgotPassword: "Şifremi Unuttum",
        loginLoading: "Yükleniyor...",
        "videoPlaceholder": "Tarayıcınız video etiketini desteklemiyor.",
        "ulusalBarter": "ULUSAL BARTER",
        "mainHeading1": "Barter Yatırımın Güvencesi:",
        "mainHeading2": "Ulusal Güç, Yerel Çözüm!",
        "subtitle": "Ulusal Barter A.Ş.",
        "subtitleHighlight": "Nakitin Ötesinde",
        "subtitleDesc": "Yenilikçi barter yatırım sistemiyle işletmeler için nakitsiz ticaretin güçlü altyapısı",
        "subtitleQuote": "Yalnızca bugününüzü değil, yarınınızı da birlikte inşa ediyoruz",
        "discoverBarter": "Barter Sistemini Keşfedin",
        "promoVideoTitle": "Ulusal Barter A.Ş. Tanıtım Videomuz",
        "promoParagraph": "Türkiye'nin önde gelen barter platformu olarak, işletmelerin değer üreten yönlerini öne çıkarıyor ve nakit sıkışıklığı yaşamadan büyümelerini sağlıyoruz. Ulusal Barter A.Ş. olarak, geleneksel finans sistemlerinin ötesinde çözümler sunuyoruz.",
        "barterBenefits": "Barter ile Elde Edeceğiniz Avantajlar",
        "barterBenefitsDesc": "Nakitsiz ticaretin sunduğu fırsatları keşfedin.",
        "cashFlow": "Nakit Akışı",
        "cashFlowDesc": "Nakit çıkışını azaltın, likiditenizi koruyun.",
        "stockManagement": "Stok Yönetimi",
        "stockManagementDesc": "Stoklarınızı değer karşılığında kullanın.",
        "marketAccess": "Pazar Erişimi",
        "marketAccessDesc": "Yeni iş bağlantıları ve müşteriler edinin.",
        "secureTrade": "Güvenilir Ticaret",
        "secureTradeDesc": "Şeffaf ve güvenli barter işlemleri.",
        "flexibleSolutions": "Esnek Çözümler",
        "flexibleSolutionsDesc": "Çeşitli ödeme ve takas imkanları.",
        "economicPower": "Ekonomik Güç",
        "economicPowerDesc": "Dalgalanmalara karşı dirençli ticaret.",
        "learnMore": "Daha Fazlasını Öğrenin",
        "latestListings": "Son Eklenen İlanlar",
        "joinAndSeeAll": "Üye Ol ve Hepsini Gör",
        "whyChooseUs": "Neden Bizi Seçmelisiniz?",
        "reason1": "Nakit harcamadan büyüme fırsatı",
        "reason2": "Stokları değere dönüştüren sistem",
        "reason3": "Türkiye genelinde güçlü ticaret ağı",
        "reason4": "Şeffaf, kayıtlı ve güvenli işlemler",
        "reason5": "Her sektöre uygun, kişiye özel çözümler",
        "reason6": "Krizlere karşı dayanıklı ticaret modeli",
        "futureMessage": "Ulusal Barter A.Ş. ile ticaretinizin geleceğini bugünden kurun.",
        "quote": "Nakitsiz ticaretin gücünü keşfedin, işletmenizin potansiyelini ortaya çıkarın. ULUSAL BARTER A.Ş. — Paradan bağımsız, değerden yana bir ekonomi modeli.",
        "contactUs": "Bize Ulaşın",
        "contactTitle": "Bizimle İletişime Geçin",
        "companySlogan": "Barter Yatırımın Güvencesi: Ulusal Güç, Yerel Çözüm!",
        "links": "Bağlantılar",
        "aboutUs": "Hakkımızda",
        "barterSystem": "Barter Sistemi",
        "membership": "Üyelik",
        "contact": "İletişim",
        "address": "Adres",
        "addressDetail": "Mansuroğlu Mah. 283/1 Sk. No:2 GSK Plaza K:1 D:201 Bayraklı/İzmir",
        "phone": "0232 600 25 25",
        "email": "ulusalbarter@gmail.com",
        "copyright": "Tüm hakları saklıdır.",
        "privacyPolicy": "Gizlilik Politikası",
        "cookies": "Çerezler",
        "terms": "Şartlar",
        "confirmMarkAsSold": "Bu ilanı 'satıldı' olarak işaretlemek istiyor musunuz?",
        "confirmMarkAsUnsold": "Bu ilanı tekrar 'satılmadı' olarak işaretlemek istiyor musunuz?",
        "deleteConfirm": "Bu ürünü silmek istediğinize emin misiniz?",
        "successOffer": "Teklif başarıyla verildi.",
        "errorOffer": "Bir hata oluştu.",
        "invalidAmount": "Geçerli bir miktar giriniz.",
        "withdrawSuccess": "Teklif geri çekildi.",
        "withdrawError": "Teklif geri çekilirken hata oluştu.",
        "offerNotFound": "Silinecek teklif bulunamadı.",
        "deleteSuccess": "Ürün silindi.",
        "deleteError": "Ürün silinirken bir hata oluştu.",
        "unknownUser": "Bilinmeyen Kullanıcı",
        "loading": "Yükleniyor...",
        "giveOffer": "Teklif Ver",
        "enterAmount": "Miktar girin",
        "cancel": "İptal",
        "submit": "Gönder",
        "listingNumber": "İlan Numarası",
        "price": "Fiyat",
        "otherMedia": "Diğer Medya",
        "productDetails": "Ürün Detayları",
        "noDescription": "Açıklama bulunamadı.",
        "edit": "Düzenle",
        "delete": "Sil",
        "markAsSold": "Satıldı İşaretle",
        "unmarkSold": "İşareti Geri Al",
        "giveOfferButton": "Teklif Ver",
        "withdrawOffer": "Teklifi Geri Çek",
        "addFavorite": "Favorilere Ekle",
        "removeFavorite": "Favorilerden Çıkar",
        "fetchUsersError": "Kullanıcılar alınırken hata oluştu.",
        "enterBalance": "Lütfen bakiye miktarı girin.",
        "invalidBalance": "Geçerli bir bakiye miktarı girin.",
        "enterDescription": "Lütfen açıklama girin.",
        "balanceAdded": "Bakiye başarıyla eklendi.",
        "balanceSubtracted": "Bakiye başarıyla çıkarıldı.",
        "insufficientBalance": "Yetersiz bakiye.",
        "errorOccurred": "Hata oluştu.",
        "userBalances": "Kullanıcı Bakiyeleri",
        "noUsersWithRole": "User rolünde kayıtlı kullanıcı bulunamadı.",
        "nameBalance": "Ad Soyad / Bakiye",
        "amount": "Miktar",
        "action": "İşlem",
        "enterAmount": "Miktar",
        "enterDescription": "Açıklama",
        "add": "Ekle",
        "subtract": "Çıkar",
        "history": "Geçmiş",
        "transactionHistory": "İşlem Geçmişi",
        "noHistory": "Geçmiş bulunamadı.",
        "addTransaction": "Ekleme",
        "subtractTransaction": "Çıkarma",
        "pendingRequests": "Onay Bekleyen İstekler",
        "noPendingRequests": "Onay bekleyen kullanıcı yok.",
        "approve": "Onayla",
        "offers": "Teklifler",
        "noOffersYet": "Henüz teklif yok.",
        "offerBy": "Teklif Veren",
        "close": "Kapat",
        "filterLocation": "Konum Ara",
        "searchPlaceholder": "İl, İlçe...",
        "type": "Tür",
        "saleStatus": "Satış Durumu",
        "all": "Tümü",
        "unsold": "Satılmayanlar",
        "sold": "Satılanlar",
        "Arsa": "Arsa",
        "Arazi": "Arazi",
        "Otel": "Otel",
        "Hizmet": "Hizmet",
        "Çiftlik": "Çiftlik",
        "Daire": "Daire",
        "Villa": "Villa",
        "Santral": "Santral",
        "Restaurant": "Restoran",
        "Bahçe": "Bahçe",
        "Tarla": "Tarla",
        "Parsel": "Parsel",
        "Tesis": "Tesis",
        "Zeytinlik": "Zeytinlik",
        "Fabrika": "Fabrika",
        "Beyaz Eşya": "Beyaz Eşya",
        "Ofis": "Ofis",
        "Ev": "Ev",
        "Malikane": "Malikane",
        "Tatil Köyü": "Tatil Köyü",
        "Taksi": "Taksi",
        "Tekstil": "Tekstil",
        "Peyzaj": "Peyzaj",
        "Sera": "Sera",
        "Estetik": "Estetik",
        "welcome": "Hoşgeldiniz",
        "productsListed": "ürün listeleniyor",
        "barterBalance": "Barter Bakiyesi",
        "accountHistory": "Hesap Geçmişi",
        "myFavorites": "Favorilerim",
        "myFavoriteListings": "Favori İlanlarım",
        "noNameListing": "İsimsiz İlan",
        "close": "Kapat",
        "noFavoritesFound": "Favorilere eklenmiş ilan bulunamadı.",
        "balanceTracking": "Bakiye Takip",
        "addProduct": "Ürün Ekle",
        "viewRequests": "İstekleri Görüntüle",
        "offers": "Teklifler",
        "filter": "Filtre",
        "logout": "Çıkış Yap",
        "noResults": "Sonuç bulunamadı",
        "noMatchingProducts": "Filtre kriterlerinize uygun ürün bulunamadı.",
        "clearFilters": "Filtreleri Temizle",
        "barterCompleted": "TAKASIMIZ GERÇEKLEŞTİRİLMİŞTİR.",
        "productPinned": "Ürün üste sabitlendi.",
        "productUnpinned": "Ürün sıralamaya geri alındı.",
        "pinToTop": "Üste Sabitle",
        "unpin": "Üstten Kaldır",
        "details": "Detay",
        "heroTitlePrefix": "Barter Sistemi:",
        "heroTitleSuffix": "İşletmenizin Geleceği",
        "heroDescription": "Ulusal Barter A.Ş. ile nakitsiz, değer odaklı ticaretin avantajlarını keşfedin.",
        "videoFallback": "Tarayıcınız video etiketini desteklemiyor.",
        "whatIsBarterTitle": "Barter Nedir ve Nasıl Çalışır?",
        "whatIsBarterDescription": "Basit, güvenli ve yenilikçi bir ticaret modeliyle tanışın.",
        "barterParagraph1": "Barter, ürünlerin ve hizmetlerin nakit para kullanmadan doğrudan takas edilmesidir. Ulusal Barter A.Ş. olarak, bu eski ticaret yöntemini modernize ederek işletmelerin yeni pazarlara açılmasını, atıl kapasitelerini değerlendirmesini ve nakit akışlarını optimize etmesini sağlıyoruz.",
        "barterParagraph2": "Sistemimiz, bir barter çeki sistemi (veya barter puanı) üzerine kuruludur. Üyelerimiz, sattıkları ürün veya hizmetler karşılığında nakit yerine barter çeki kazanır ve bu çekleri sistemdeki diğer üyelerden ihtiyaç duydukları ürün veya hizmetleri almak için kullanır. Bu sayede, işletmeler nakitlerini koruyarak değerlerini katlar.",
        "barterParagraph3": "Ulusal Barter A.Ş.'nin uzman kadrosu, tüm ticaret süreçlerinizde size rehberlik eder, güvenli ve şeffaf bir platform sunar.",
        "benefit1Title": "Değer Takası",
        "benefit1Desc": "Ürün ve hizmetlerinizi nakitsiz takas edin.",
        "benefit2Title": "Nakit Koruma",
        "benefit2Desc": "İşletmenizin likiditesini artırın.",
        "benefit3Title": "Geniş Ağ",
        "benefit3Desc": "Binlerce firmaya erişim sağlayın.",
        "benefit4Title": "Güvenli İşlem",
        "benefit4Desc": "Tüm işlemler güvence altında.",
        "barterStepsTitle": "Barter Süreci: Kolay ve Hızlı Adımlar",
        "barterStepsDesc": "Ulusal Barter A.Ş. ile takas yapmak işte bu kadar kolay!",
        "step1Title": "Üyelik ve Tanımlama",
        "step1Desc": "İşletmenizi kaydedin, ürün ve hizmetlerinizi tanımlayın...",
        "step2Title": "Ticaret ve Çek Kazanma",
        "step2Desc": "Tanımladığınız ürünleri satın, barter çeki kazanın.",
        "step3Title": "İhtiyaçlarınızı Karşılama",
        "step3Desc": "Barter çekleri ile ihtiyaçlarınızı alın.",
        "step4Title": "Büyüme ve Kazanç",
        "step4Desc": "Atıl kapasitenizi değerlendirin, kazanç sağlayın.",
        "faqTitle": "Sıkça Sorulan Sorular",
        "faqDescription": "Barter sistemi hakkında merak ettikleriniz.",
        "faq1Q": "Barter sistemi nedir?",
        "faq1A": "Barter, nakit para kullanmadan ürün ve hizmetlerin doğrudan takas edildiği bir ticaret yöntemidir. Ulusal Barter A.Ş. sistemi, üyelerin sattıkları ürün ve hizmetler karşılığında barter çeki kazanıp, bu çeklerle diğer üyelerden ihtiyaçlarını karşılamasını sağlar.",
        "faq2Q": "Kimler barter yapabilir?",
        "faq2A": "Her sektörden ve her büyüklükten işletme, barter sistemine dahil olabilir. Özellikle atıl kapasitesi veya stoğu olan firmalar için büyük avantajlar sunar. Barter sistemimiz, geniş bir üye ağına sahiptir.",
        "faq3Q": "Barter çekleri nasıl kullanılır?",
        "faq3A": "Kazandığınız barter çekleri, Ulusal Barter A.Ş. platformunda listelenen diğer tüm ürün ve hizmetler için kullanılabilir. Çekler, nakit gibi değerlendirilir ve sistem içindeki tüm ticari faaliyetlerde geçerlidir.",
        "faq4Q": "Güvenli mi?",
        "faq4A": "Evet, Ulusal Barter A.Ş. olarak tüm ticari işlemlerde şeffaflık ve güvenliği ön planda tutuyoruz. Her işlem kayıt altına alınır ve olası anlaşmazlıklarda profesyonel destek sağlanır.",
        "faq5Q": "Barter sistemi işletmeme ne gibi faydalar sağlar?",
        "faq5A": "Nakit akışı optimizasyonu, atıl stokların değerlendirilmesi, yeni müşterilere ulaşım, pazar payı artışı ve ekonomik dalgalanmalara karşı direnç gibi pek çok fayda sağlar.",
        "ctaTitle": "Siz de Barter Dünyasına Katılın!",
        "ctaDescription": "İşletmenizin geleceğini dönüştürmek ve nakitsiz ticaretin avantajlarından faydalanmak için bugün bize ulaşın.",
        "ctaButton": "Hemen Üye Olun"
    },
    en: {
        'language': 'Language',
        'turkish': 'Turkish',
        'english': 'English',
        'german': 'German',
        'balanceTracking': 'Balance Tracking',
        'balance': 'Balance',
        'addBalance': 'Add Balance',
        'removeBalance': 'Remove Balance',
        'amount': 'Amount',
        'description': 'Description',
        'cancel': 'Cancel',
        'add': 'Add',
        'remove': 'Remove',
        'history': 'History',
        'invalidInput': 'Enter a valid amount and description',
        'belowZeroError': 'Balance cannot go below zero!',
        'noUsersFound': 'No users found',
        'errorOccurred': 'An error occurred',
        'noTransactionHistory': 'No transaction history found.',
        'months': [
            'January',
            'February',
            'March',
            'April',
            'May',
            'June',
            'July',
            'August',
            'September',
            'October',
            'November',
            'December',
        ],
        'listings': 'Listings',
        'profile': 'Profile',
        'about': 'About Us',
        'barter': 'Barter System',
        'contact': 'Contact',
        'logout': 'Logout',
        'deleteAccount': 'Delete Account',
        'barterSystem': 'Barter System',
        'aboutUs': 'About Us',
        'about1':
            "ULUSAL Barter Inc. was established with the aim of bringing a new breath to the commercial activities of our country with the barter system, which is widely used in the world.",
        'about2':
            "With its strong capital and rational trade approach, its contribution to the economy, as well as its corporate structure, its professional team, which takes ownership of its work, uses its creativity in solving problems, and produces rational solutions, ULUSAL Barter Inc. is the strongest representative of the developing sector.",
        'about3':
            "Increasing its success every year, ULUSAL Barter Inc. has taken part in many joint projects with the leading large holdings of the country; with its service policy, it has received positive references from the works it has taken part in. Enriching its portfolio with the power of the positive references it has gained, ULUSAL Barter Inc. has reached over 5000 members.",
        'about4':
            "The success it has achieved with the support of its increasing number of members and strategic partners contributes to the recognition of the developing barter sector in our country as an innovative, visionary and profitable trade system.",
        'about5': "While developing value-added foreign trade projects;",
        'about6':
            "✓ Acting with the mission, vision and strategy of ULUSAL Barter A.Ş., to carry out all kinds of foreign and domestic trade operations as Ram Domestic and Foreign Trade by meeting the needs and expectations of the relevant parties,",
        'about7':
            "✓ While aiming to provide the best and perfect service with its customer-focused strategy; not to compromise on business ethics and reliable stance,",
        'about8':
            "✓ To be a pioneer in the sector with its 26 years of experience in the foreign and domestic trade sector, its knowledge and expert team, and to develop by taking steps that will set sector standards,",
        'about9':
            "✓ To provide the most efficient and optimum solutions to institutions through financial services in export activities that will contribute to the country's economy,",
        'about10':
            "✓ Carrying along its employees and stakeholders in its quality journey with its flawless service mission and continuously improving,",
        'about11':
            "✓ While fulfilling the compliance obligations with national and/or international regulations; also increasing the awareness of stakeholders and employees by signing environmentally friendly approaches and social responsibility projects,",
        'about12':
            "✓ Continuously digitalizing the quality of operations and services by following technological developments and using innovative approaches,",
        'about13':
            "✓ Undertaking to achieve the difficult and reach its goals by transferring the knowledge and sector experience accumulated through all these activities to corporate memory with the quality management system and ensuring continuity by constantly improving the system.",
        'about14': "Our Mission and Values",
        'about15':
            "To make our country a center of attraction for trade and investments and continuously improve the quality of life, to facilitate the commercial activities of its members with innovative and original projects developed by using resources effectively, and to offer sustainable services to the business world and society.",
        'about16': "Our Vision for the Future",
        'about17':
            "To become Turkey’s role model barter company in life, trade, and investment by guiding its members in their sectoral development and transformation processes in line with the goals of sustainable development and creating value together with its stakeholders.",
        'about18': "Chairman of the Board",
        'about19': "Vice Chairman of the Board",
        'about20': "Board Member",
        'about21': "Marketing Coordinator",
        'about22': "Media Promotion Coordinator",
        'about23': "IT Coordinator",
        'about24': "Customer Coordinator",
        'about25': "Legal Coordinator",
        'about26': "Accounting Coordinator",
        'about27': "Real Estate Coordinator",
        'about28': "Customer Representative",
        'about29': "Board of Directors",
        'about30': "Purpose of Establishment",
        'about31': "Corporate Structure and Strong Team",
        'about32': "Success and References",
        'about33': "Contribution to the Sector",
        'about34': "Operating Principles and Goals",
        "about35": "General Information",
        "about36": "Our Mission",
        "about37": "Our Vision",
        'contactSubtitle': 'Feel free to get in touch with us.',
        'contactInfo': 'Contact Information',
        'email': 'E-Mail',
        'phone': 'Phone',
        'address': 'Address',
        'register': 'Register',
        'firstName': 'First Name',
        'lastName': 'Last Name',
        'password': 'Password',
        'genericError': 'An error occurred.',
        'login': 'Login',
        'forgotPassword': 'Forgot Password',
        'loginFailed': 'Login failed. Please check your credentials.',
        'userNotFound': 'User not found or account has been deleted.',
        'notApproved': 'Your account is not yet approved by the admin.',
        'userDataNotFound': 'User data not found.',
        'openMenu': 'Open Menu',
        'myProfile': 'My Profile',
        'save': 'Save',
        'edit': 'Edit',
        'updated': 'Information updated',
        'emailLabel': 'Your email address',
        'sendResetLink': 'Send Password Reset Link',
        'sending': 'Sending...',
        'goBack': 'Go Back',
        'resetLinkSent': 'Password reset link has been sent to your email.',
        'resetError': 'An error occurred. Please check your email address.',
        'offers': 'Offers',
        'offeredBy': 'Offered by',
        'noOffersYet': 'No offers yet',
        'unknownUser': 'Unknown',
        addProduct: "Add Product",
        productName: "Product Name",
        price: "Price",
        selectMainImage: "Select Main Image",
        addExtraImages: "Add Extra Images",
        addVideo: "Add Video",
        addDesc: "Add Description",
        removeDesc: "Remove Description",
        saveProduct: "Save Product",
        fillRequiredFields: "Please enter product name, price, and main image.",
        productSaved: "Product saved successfully.",
        productNotFound: "Product to edit not found.",
        productFetchError: "Error while fetching product",
        userNotFound: "User info not available.",

        'favoriteAdded': 'Added to favorites',
        'favoriteRemoved': 'Removed from favorites',
        'offerExists': 'Offer already exists',
        'productSold': 'Sold',
        'makeOffer': 'Make Offer',
        'withdrawOffer': 'Withdraw Offer',
        'addFavorite': 'Add to Favorites',
        'removeFavorite': 'Remove from Favorites',
        'invalidAmount': 'Enter a valid amount',
        'successfull': 'Offer sent successfully',
        'withdrawnOffer': 'The offer was withdrawn',
        'markAsSold': 'Mark as Sold',
        'unmarkSold': 'Unmark Sold',
        'confirmMarkAsSold': 'Do you really want to mark this product as sold?',
        'confirmRemoveSoldMark':
            'Do you want to remove the sold mark from this product?',
        'yes': 'Yes',
        'deleteProduct': 'Delete Product',
        'confirmDeleteProduct': 'Are you sure you want to delete this product?',
        'delete': 'Delete',
        'productDetails': 'Product Details',
        'listingNumber': 'Listing Number: ',
        'loginToSeePrice': 'Login to see the price',
        'otherMedia': 'Other Media',
        'searchLocation': 'Search Location',
        'hintLocation': 'City, district...',
        'type': 'Type',
        'status': 'Status',
        'all': 'All',
        'sold': 'Sold',
        'unsold': 'Unsold',
        'loadingContent': 'Loading content...',
        'welcomeUser': 'Welcome',
        'productCount': 'products listed',
        'requests': 'Requests',
        'filter': 'Filter',
        'accountHistory': 'Account History',
        'favorites': 'Favorites',
        'noFavoritesFound': 'No favorite ads found.',
        'close': 'Close',
        'myFavoriteAds': 'My Favorite Ads',
        'ad': 'Ad',
        'myFavorites': 'My Favorites',
        'noProductsFound': 'No products found.',
        'unnamedProduct': 'Unnamed Product',
        'detail': 'Detail',
        'swapCompleted': 'BARTER COMPLETED',
        'pinned': 'Pinned to top',
        'unpinned': 'Returned to sorting',
        'pin': 'Pin',
        'unpin': 'Unpin',
        'noPendingUsers': 'No pending users.',
        'pendingUsers': 'Pending Users',
        'productTypes': [
            "Land", "Field", "Hotel", "Service", "Farm",
            "Apartment", "Villa", "Power Plant", "Restaurant", "Garden",
            "Farmland", "Plot", "Facility", "Olive Grove", "Factory",
            "White Goods", "Office", "House", "Mansion", "Holiday Village",
            "Taxi", "Textile", "Landscape", "Greenhouse", "Aesthetics",
        ],
        "navbar.home": "Home",
        "navbar.about": "About Us",
        "navbar.barter": "Barter System",
        "navbar.products": "Products & Services",
        "navbar.contact": "Contact",
        "navbar.joinNow": "Join Now",
        contactPageTitle: "CONTACT",
        contactPageSubtitle: "Feel free to get in touch with us.",
        contactInfoTitle: "Contact Information",
        contactEmailLabel: "Email",
        contactPhoneLabel: "Phone",
        contactAddressLabel: "Address",
        contactAddress: "Mansuroğlu Mah. 283/1 Sk. No:2 GSK Plaza Floor:1 Apt:201 Bayraklı/İzmir",
        contactFormTitle: "Send a Message",
        contactFormName: "Full Name",
        contactFormEmail: "Email",
        contactFormPhone: "Phone",
        contactFormMessage: "Your Message",
        contactFormSubmit: "Send Message",
        contactFormSuccess: "Your message has been sent successfully!",
        contactFormError: "An error occurred, please try again.",
        registerTitle: "Sign Up",
        registerPlaceholderFirstName: "First Name",
        registerPlaceholderLastName: "Last Name",
        registerPlaceholderPhone: "Phone",
        registerPlaceholderAddress: "Address",
        registerPlaceholderEmail: "Email",
        registerPlaceholderPassword: "Password",
        registerErrorApproval: "Your account is awaiting admin approval.",
        registerErrorGeneral: "Registration failed. Please check your information.",
        registerButton: "Sign Up",
        registerWarning: "Warning!",
        forgotTitle: "Forgot Password",
        forgotPlaceholderEmail: "Your email address",
        forgotSending: "Sending...",
        forgotButton: "Send Password Reset Link",
        forgotError: "An error occurred. Please check your email address.",
        forgotSuccess: "Password reset link has been sent to your email. Please check your inbox.",
        loginTitle: "Login",
        loginEmail: "Email",
        loginPassword: "Password",
        loginErrorApprove: "Your account has not been approved yet. Please wait for admin approval.",
        loginErrorNotFound: "User information not found.",
        loginErrorFailed: "Login failed. Please check your credentials.",
        loginButton: "Login",
        loginRegister: "Register",
        loginForgotPassword: "Forgot Password",
        loginLoading: "Loading...",
        "videoPlaceholder": "Your browser does not support the video tag.",
        "ulusalBarter": "ULUSAL BARTER",
        "mainHeading1": "Barter Investment Assurance:",
        "mainHeading2": "National Power, Local Solution!",
        "subtitle": "Ulusal Barter Inc.",
        "subtitleHighlight": "Beyond Cash",
        "subtitleDesc": "A strong infrastructure for cashless trade with our innovative barter investment system",
        "subtitleQuote": "We build not just your today, but your tomorrow together",
        "discoverBarter": "Discover the Barter System",
        "promoVideoTitle": "Ulusal Barter Inc. Promo Video",
        "promoParagraph": "As Turkey’s leading barter platform, we highlight the value-generating aspects of businesses and help them grow without experiencing cash constraints. At Ulusal Barter Inc., we offer solutions beyond traditional financial systems.",
        "barterBenefits": "Advantages You'll Gain with Barter",
        "barterBenefitsDesc": "Explore the opportunities of cashless trade.",
        "cashFlow": "Cash Flow",
        "cashFlowDesc": "Reduce cash outflows and preserve liquidity.",
        "stockManagement": "Inventory Management",
        "stockManagementDesc": "Utilize your stock in exchange for value.",
        "marketAccess": "Market Access",
        "marketAccessDesc": "Gain new business connections and customers.",
        "secureTrade": "Secure Trading",
        "secureTradeDesc": "Transparent and safe barter transactions.",
        "flexibleSolutions": "Flexible Solutions",
        "flexibleSolutionsDesc": "Various payment and trade options.",
        "economicPower": "Economic Strength",
        "economicPowerDesc": "Trade resistant to economic fluctuations.",
        "learnMore": "Learn More",
        "latestListings": "Latest Listings",
        "joinAndSeeAll": "Join and See All",
        "whyChooseUs": "Why Choose Us?",
        "reason1": "Opportunity to grow without spending cash",
        "reason2": "System that turns inventory into value",
        "reason3": "Strong trade network across Turkey",
        "reason4": "Transparent, recorded, and secure transactions",
        "reason5": "Custom solutions for every sector",
        "reason6": "Trade model resilient to crises",
        "futureMessage": "Build the future of your trade today with Ulusal Barter Inc.",
        "quote": "Discover the power of cashless trade and unleash your business potential. ULUSAL BARTER INC. — An economy model based on value, not money.",
        "contactUs": "Contact Us",
        "contactTitle": "Get in Touch With Us",
        "companySlogan": "Barter Investment Assurance: National Power, Local Solution!",
        "links": "Links",
        "aboutUs": "About Us",
        "barterSystem": "Barter System",
        "membership": "Membership",
        "contact": "Contact",
        "address": "Address",
        "addressDetail": "Mansuroğlu Neighborhood, 283/1 St. No:2 GSK Plaza Floor:1 Apt:201 Bayraklı/İzmir",
        "phone": "0232 600 25 25",
        "email": "ulusalbarter@gmail.com",
        "copyright": "All rights reserved.",
        "privacyPolicy": "Privacy Policy",
        "cookies": "Cookies",
        "terms": "Terms",
        "confirmMarkAsSold": "Do you want to mark this listing as 'sold'?",
        "confirmMarkAsUnsold": "Do you want to mark this listing as 'unsold' again?",
        "deleteConfirm": "Are you sure you want to delete this product?",
        "successOffer": "Offer submitted successfully.",
        "errorOffer": "An error occurred.",
        "invalidAmount": "Please enter a valid amount.",
        "withdrawSuccess": "Offer withdrawn.",
        "withdrawError": "An error occurred while withdrawing the offer.",
        "offerNotFound": "No offer found to delete.",
        "deleteSuccess": "Product deleted.",
        "deleteError": "An error occurred while deleting the product.",
        "unknownUser": "Unknown User",
        "loading": "Loading...",
        "giveOffer": "Make an Offer",
        "enterAmount": "Enter amount",
        "cancel": "Cancel",
        "submit": "Submit",
        "listingNumber": "Listing Number",
        "price": "Price",
        "otherMedia": "Other Media",
        "productDetails": "Product Details",
        "noDescription": "No description found.",
        "edit": "Edit",
        "delete": "Delete",
        "markAsSold": "Mark as Sold",
        "unmarkSold": "Undo Sold",
        "giveOfferButton": "Make an Offer",
        "withdrawOffer": "Withdraw Offer",
        "addFavorite": "Add to Favorites",
        "removeFavorite": "Remove from Favorites",
        "fetchUsersError": "An error occurred while fetching users.",
        "enterBalance": "Please enter a balance amount.",
        "invalidBalance": "Enter a valid balance amount.",
        "enterDescription": "Please enter a description.",
        "balanceAdded": "Balance added successfully.",
        "balanceSubtracted": "Balance subtracted successfully.",
        "insufficientBalance": "Insufficient balance.",
        "errorOccurred": "An error occurred.",
        "userBalances": "User Balances",
        "noUsersWithRole": "No users registered with role 'user'.",
        "nameBalance": "Name / Balance",
        "amount": "Amount",
        "action": "Action",
        "enterAmount": "Enter amount",
        "enterDescription": "Enter description",
        "add": "Add",
        "subtract": "Subtract",
        "history": "History",
        "transactionHistory": "Transaction History",
        "noHistory": "No history found.",
        "addTransaction": "Addition",
        "subtractTransaction": "Subtraction",
        "pendingRequests": "Pending Requests",
        "noPendingRequests": "No pending users.",
        "approve": "Approve",
        "offers": "Offers",
        "noOffersYet": "No offers yet.",
        "offerBy": "Offered By",
        "close": "Close",
        "filterLocation": "Search Location",
        "searchPlaceholder": "City, region, district...",
        "type": "Type",
        "saleStatus": "Sale Status",
        "all": "All",
        "unsold": "Unsold",
        "sold": "Sold",
        "Arsa": "Land",
        "Arazi": "Field",
        "Otel": "Hotel",
        "Hizmet": "Service",
        "Çiftlik": "Farm",
        "Daire": "Apartment",
        "Villa": "Villa",
        "Santral": "Power Plant",
        "Restaurant": "Restaurant",
        "Bahçe": "Garden",
        "Tarla": "Farmland",
        "Parsel": "Plot",
        "Tesis": "Facility",
        "Zeytinlik": "Olive Grove",
        "Fabrika": "Factory",
        "Beyaz Eşya": "White Goods",
        "Ofis": "Office",
        "Ev": "Home",
        "Malikane": "Mansion",
        "Tatil Köyü": "Resort",
        "Taksi": "Taxi",
        "Tekstil": "Textile",
        "Peyzaj": "Landscape",
        "Sera": "Greenhouse",
        "Estetik": "Aesthetic",
        "welcome": "Welcome",
        "productsListed": "products listed",
        "barterBalance": "Barter Balance",
        "accountHistory": "Account History",
        "myFavorites": "My Favorites",
        "myFavoriteListings": "My Favorite Listings",
        "noNameListing": "Unnamed Listing",
        "close": "Close",
        "noFavoritesFound": "No favorite listings found.",
        "balanceTracking": "Balance Tracking",
        "addProduct": "Add Product",
        "viewRequests": "View Requests",
        "offers": "Offers",
        "filter": "Filter",
        "logout": "Logout",
        "noResults": "No results found",
        "noMatchingProducts": "No products match your filter criteria.",
        "clearFilters": "Clear Filters",
        "barterCompleted": "BARTER COMPLETED",
        "productPinned": "Product pinned to top.",
        "productUnpinned": "Product unpinned from top.",
        "pinToTop": "Pin to Top",
        "unpin": "Unpin",
        "details": "Details",
        "heroTitlePrefix": "Barter System:",
        "heroTitleSuffix": "The Future of Your Business",
        "heroDescription": "Discover the benefits of cashless, value-driven trade with Ulusal Barter Inc.",
        "videoFallback": "Your browser does not support the video tag.",
        "whatIsBarterTitle": "What is Barter and How Does It Work?",
        "whatIsBarterDescription": "Get to know a simple, safe, and innovative trade model.",
        "barterParagraph1": "Barter is the direct exchange of goods and services without the use of cash. At Ulusal Barter Inc., we modernize this ancient trading method to help businesses expand into new markets, utilize idle capacity, and optimize their cash flow.",
        "barterParagraph2": "Our system is based on a barter credit (or barter point) model. Our members earn barter credits instead of cash when selling goods or services, and they can use these credits to purchase the products or services they need from other members within the system. This allows businesses to preserve their cash and increase their value.",
        "barterParagraph3": "The expert team at Ulusal Barter Inc. guides you through all trade processes and provides a secure and transparent platform.",
        "benefit1Title": "Value Exchange",
        "benefit1Desc": "Trade your products and services without cash.",
        "benefit2Title": "Cash Protection",
        "benefit2Desc": "Increase your company's liquidity.",
        "benefit3Title": "Wide Network",
        "benefit3Desc": "Access thousands of companies.",
        "benefit4Title": "Secure Transactions",
        "benefit4Desc": "All transactions are guaranteed.",
        "barterStepsTitle": "Barter Process: Easy and Fast Steps",
        "barterStepsDesc": "It's that easy to barter with Ulusal Barter Inc.!",
        "step1Title": "Membership and Definition",
        "step1Desc": "Register your business, define your products and services...",
        "step2Title": "Trading and Earning Checks",
        "step2Desc": "Sell your defined products, earn barter checks.",
        "step3Title": "Meeting Your Needs",
        "step3Desc": "Use barter checks to get the products and services you need.",
        "step4Title": "Growth and Profit",
        "step4Desc": "Utilize idle capacity and enjoy financial flexibility.",
        "faqTitle": "Frequently Asked Questions",
        "faqDescription": "Things you're curious about the barter system.",
        "faq1Q": "What is the barter system?",
        "faq1A": "Barter is a method of trading in which goods and services are exchanged directly without using money. Ulusal Barter Inc.'s system allows members to earn barter checks and use them to fulfill their needs from other members.",
        "faq2Q": "Who can use barter?",
        "faq2A": "Businesses of all sizes and industries can join the barter system. It offers significant advantages, especially for companies with idle stock or capacity. Our system includes a wide network of members.",
        "faq3Q": "How are barter checks used?",
        "faq3A": "The barter checks you earn can be used for any product or service listed on the Ulusal Barter Inc. platform. They are treated like cash and are valid for all commercial transactions within the system.",
        "faq4Q": "Is it safe?",
        "faq4A": "Yes, at Ulusal Barter Inc. we prioritize transparency and security in all transactions. Every transaction is recorded and professional support is provided in case of disputes.",
        "faq5Q": "What benefits does the barter system offer my business?",
        "faq5A": "It offers benefits such as optimized cash flow, utilization of idle stock, access to new customers, increased market share, and resistance to economic fluctuations.",
        "ctaTitle": "Join the World of Barter!",
        "ctaDescription": "Transform your business future and benefit from the advantages of cashless trade. Contact us today.",
        "ctaButton": "Join Now"
    },
    de: {
        'language': 'Sprache',
        'turkish': 'Türkisch',
        'english': 'Englisch',
        'german': 'Deutsch',
        'balanceTracking': 'Kontostand-Überwachung',
        'balance': 'Kontostand',
        'addBalance': 'Guthaben hinzufügen',
        'removeBalance': 'Guthaben entfernen',
        'amount': 'Betrag',
        'description': 'Beschreibung',
        'cancel': 'Abbrechen',
        'add': 'Hinzufügen',
        'remove': 'Entfernen',
        'history': 'Verlauf',
        'invalidInput':
            'Geben Sie einen gültigen Betrag und eine Beschreibung ein',
        'belowZeroError': 'Kontostand kann nicht negativ sein!',
        'noUsersFound': 'Keine Benutzer gefunden',
        'errorOccurred': 'Ein Fehler ist aufgetreten',
        'noTransactionHistory': 'Keine Transaktionshistorie gefunden.',
        'months': [
            'Januar',
            'Februar',
            'März',
            'April',
            'Mai',
            'Juni',
            'Juli',
            'August',
            'September',
            'Oktober',
            'November',
            'Dezember',
        ],
        'listings': 'Anzeigen',
        'profile': 'Profil',
        'about': 'Über uns',
        'barter': 'Tauschsystem',
        'contact': 'Kontakt',
        'logout': 'Abmelden',
        'deleteAccount': 'Konto löschen',
        'barterSystem': 'Tauschsystem',
        'aboutUs': 'Über uns',
        'about1':
            "ULUSAL Barter Inc. wurde mit dem Ziel gegründet, den Handelsaktivitäten unseres Landes mit dem weltweit weit verbreiteten Tauschsystem neuen Schwung zu verleihen.",
        'about2':
            "Mit seinem starken Kapital und rationalen Handelsansatz, seinem Beitrag zur Wirtschaft sowie seiner Unternehmensstruktur und seinem professionellen Team, das Verantwortung für seine Arbeit übernimmt, seine Kreativität bei der Lösung von Problemen einsetzt und rationale Lösungen hervorbringt, ist ULUSAL Barter Inc. der stärkste Vertreter des Entwicklungssektors.",
        'about3':
            "ULUSAL Barter Inc. steigert seinen Erfolg jedes Jahr und hat an vielen gemeinsamen Projekten mit den führenden Großkonzernen des Landes teilgenommen. Dank seiner Servicepolitik hat das Unternehmen für die Arbeiten, an denen es beteiligt war, positive Referenzen erhalten. Dank der positiven Referenzen, die es erhalten hat, konnte ULUSAL Barter Inc. sein Portfolio erweitern und hat mittlerweile über 5.000 Mitglieder.",
        'about4':
            "Der mit der Unterstützung der wachsenden Zahl an Mitgliedern und strategischen Partnern erzielte Erfolg trägt zur Anerkennung des sich entwickelnden Tauschsektors in unserem Land als innovatives, visionäres und profitables Handelssystem bei.",
        'about5': "Bei der Entwicklung wertschöpfender Außenhandelsprojekte;",
        'about6':
            "✓ Handeln im Sinne der Mission, Vision und Strategie von ULUSAL Barter A.Ş., alle Arten von Außen- und Inlandshandelsgeschäften als Ram Domestic and Foreign Trade durchzuführen und dabei die Bedürfnisse und Erwartungen der jeweiligen Parteien zu erfüllen,",
        'about7':
            "✓ Mit dem Ziel, mit seiner kundenorientierten Strategie den besten und perfekten Service zu bieten, ohne Kompromisse bei der Geschäftsethik und der zuverlässigen Haltung einzugehen,",
        'about8':
            "✓ Mit seiner 26-jährigen Erfahrung im Außen- und Binnenhandel, seinem Wissen und seinem Expertenteam ein Pionier in der Branche zu sein und sich durch Schritte weiterzuentwickeln, die Branchenstandards setzen,",
        'about9':
            "✓ Bereitstellung der effizientesten und optimalen Lösungen für Institutionen durch Finanzdienstleistungen im Exportbereich, die zur Wirtschaft des Landes beitragen,",
        'about10':
            "✓ Die Mitarbeiter und interessierten Parteien auf dem Weg zur Qualität mitzunehmen und kontinuierlich zu verbessern – mit der Mission eines fehlerfreien Service,",
        'about11':
            "✓ Während der Einhaltung nationaler und/oder internationaler Vorschriften auch durch umweltfreundliche Ansätze und soziale Projekte das Bewusstsein der Beteiligten und Mitarbeiter zu stärken,",
        'about12':
            "✓ Durch Verfolgung technologischer Entwicklungen und innovative Ansätze die Qualität von Betrieb und Dienstleistung kontinuierlich zu digitalisieren,",
        'about13':
            "✓ Beim Erreichen anspruchsvoller Ziele das gesammelte Wissen und die Branchenerfahrung in das Unternehmensgedächtnis aufzunehmen und durch ständige Weiterentwicklung fortzuführen.",
        'about14': "Unsere Mission und Werte",
        'about15':
            "Unser Land zu einem Anziehungspunkt für Handel und Investitionen zu machen, die Lebensqualität stetig zu verbessern, die Handelsaktivitäten seiner Mitglieder durch effektiven Ressourceneinsatz und innovative Projekte zu erleichtern und nachhaltige Dienstleistungen für Wirtschaft und Gesellschaft zu bieten.",
        'about16': "Unsere Vision für die Zukunft",
        'about17':
            "Ein Vorbild-Barterunternehmen unseres Landes in Leben, Handel und Investitionen zu sein, das seine Mitglieder bei der branchenspezifischen Entwicklung begleitet und gemeinsam mit den Stakeholdern Werte schafft – im Einklang mit den Zielen nachhaltiger Entwicklung.",
        'about18': "Vorsitzender des Vorstands",
        'about19': "Stellvertretender Vorsitzender des Vorstands",
        'about20': "Vorstandsmitglied",
        'about21': "Marketing-Koordinator",
        'about22': "Medien- und Werbungskoordinator",
        'about23': "IT-Koordinator",
        'about24': "Kundenkoordinator",
        'about25': "Rechtskoordinator",
        'about26': "Buchhaltungskoordinator",
        'about27': "Immobilienkoordinator",
        'about28': "Kundenbetreuer",
        'about29': "Vorstand",
        "about30": "Zweck der Gründung",
        "about31": "Unternehmensstruktur und Starkes Team",
        "about32": "Erfolg und Referenzen",
        "about33": "Beitrag zum Sektor",
        "about34": "Betriebsgrundsätze und Ziele",
        "about35": "Allgemeine Informationen",
        "about36": "Unsere Mission",
        "about37": "Unsere Vision",
        'contactSubtitle': 'Zögern Sie nicht, uns zu kontaktieren.',
        'contactInfo': 'Kontaktinformationen',
        'email': 'E-Mail',
        'phone': 'Telefon',
        'address': 'Adresse',
        'register': 'Registrieren',
        'firstName': 'Vorname',
        'lastName': 'Nachname',
        'password': 'Passwort',
        'genericError': 'Ein Fehler ist aufgetreten.',
        'login': 'Anmelden',
        'forgotPassword': 'Passwort vergessen',
        'loginFailed': 'Anmeldung fehlgeschlagen. Bitte prüfen Sie Ihre Daten.',
        'userNotFound': 'Benutzer nicht gefunden oder Konto wurde gelöscht.',
        'notApproved': 'Ihr Konto wurde noch nicht vom Administrator genehmigt.',
        'userDataNotFound': 'Benutzerdaten wurden nicht gefunden.',
        'openMenu': 'Menü öffnen',
        'myProfile': 'Mein Profil',
        'save': 'Speichern',
        'edit': 'Bearbeiten',
        'updated': 'Informationen wurden aktualisiert',
        'emailLabel': 'Ihre E-Mail-Adresse',
        'sendResetLink': 'Passwort-Reset-Link senden',
        'sending': 'Wird gesendet...',
        'goBack': 'Zurück',
        'resetLinkSent': 'Passwort-Reset-Link wurde an Ihre E-Mail gesendet.',
        'resetError':
            'Ein Fehler ist aufgetreten. Bitte überprüfen Sie Ihre E-Mail-Adresse.',
        'offers': 'Angebote',
        'offeredBy': 'Angeboten von',
        'noOffersYet': 'Noch keine Angebote',
        'unknownUser': 'Unbekannt',
        addProduct: "Produkt hinzufügen",
        productName: "Produktname",
        price: "Preis",
        selectMainImage: "Hauptbild auswählen",
        addExtraImages: "Zusätzliche Bilder hinzufügen",
        addVideo: "Video hinzufügen",
        addDesc: "Beschreibung hinzufügen",
        removeDesc: "Beschreibung entfernen",
        saveProduct: "Produkt speichern",
        fillRequiredFields: "Bitte Produktname, Preis und Hauptbild eingeben.",
        productSaved: "Produkt erfolgreich gespeichert.",
        productNotFound: "Zu bearbeitendes Produkt nicht gefunden.",
        productFetchError: "Fehler beim Abrufen des Produkts",
        userNotFound: "Benutzerinformationen nicht verfügbar.",
        'favoriteAdded': 'Zu Favoriten hinzugefügt',
        'favoriteRemoved': 'Aus Favoriten entfernt',
        'offerExists': 'Angebot existiert bereits',
        'productSold': 'Verkauft',
        'makeOffer': 'Angebot machen',
        'withdrawOffer': 'Angebot zurückziehen',
        'addFavorite': 'Zu Favoriten hinzufügen',
        'removeFavorite': 'Aus Favoriten entfernen',
        'invalidAmount': 'Geben Sie einen gültigen Betrag',
        'successfull': 'Angebot erfolgreich versendet',
        'withdrawnOffer': 'Das Angebot wurde zurückgezogen',
        'markAsSold': 'Verkauft Markieren',
        'unmarkSold': 'Markier Entfernen',
        'confirmMarkAsSold':
            'Möchten Sie dieses Produkt wirklich als verkauft markieren?',
        'confirmRemoveSoldMark':
            'Möchten Sie die Verkauft-Markierung von diesem Produkt entfernen?',
        'yes': 'Ja',
        'deleteProduct': 'Produkt löschen',
        'confirmDeleteProduct':
            'Sind Sie sicher, dass Sie dieses Produkt löschen möchten?',
        'delete': 'Löschen',
        'productDetails': 'Produktdetails',
        'listingNumber': 'Anzeigenummer: ',
        'loginToSeePrice': 'Melden Sie sich an, um den Preis zu sehen',
        'otherMedia': 'Weitere Medien',
        'searchLocation': 'Standort suchen',
        'hintLocation': 'Stadt, Bezirk...',
        'type': 'Typ',
        'status': 'Status',
        'all': 'Alle',
        'sold': 'Verkauft',
        'unsold': 'Nicht verkauft',
        'loadingContent': 'Inhalt wird geladen...',
        'welcomeUser': 'Willkommen',
        'productCount': 'Produkte aufgelistet',
        'requests': 'Anfragen',
        'filter': 'Filter',
        'accountHistory': 'Kontoverlauf',
        'favorites': 'Favoriten',
        'noFavoritesFound': 'Keine favorisierten Anzeigen gefunden.',
        'close': 'Schließen',
        'myFavoriteAds': 'Meine Favoritenanzeigen',
        'ad': 'Anzeige',
        'myFavorites': 'Meine Favoriten',
        'noProductsFound': 'Keine Produkte gefunden.',
        'unnamedProduct': 'Unbenanntes Produkt',
        'detail': 'Details',
        'swapCompleted': 'TAUSCH ABGESCHLOSSEN',
        'pinned': 'Oben angeheftet',
        'unpinned': 'Zurück zur Sortierung',
        'pin': 'Anheften',
        'unpin': 'Lösen',
        'noPendingUsers': 'Keine Benutzer zur Genehmigung.',
        'pendingUsers': 'Benutzer zur Genehmigung',
        'productTypes': [
            "Grundstück", "Feld", "Hotel", "Dienstleistung", "Bauernhof",
            "Wohnung", "Villa", "Kraftwerk", "Restaurant", "Garten",
            "Ackerland", "Parzelle", "Anlage", "Olivenhain", "Fabrik",
            "Weiße Ware", "Büro", "Haus", "Villa", "Ferienort",
            "Taxi", "Textil", "Landschaft", "Gewächshaus", "Ästhetik",
        ],
        "navbar.home": "Startseite",
        "navbar.about": "Über Uns",
        "navbar.barter": "Barter-System",
        "navbar.products": "Produkte & Dienstleistungen",
        "navbar.contact": "Kontakt",
        "navbar.joinNow": "Jetzt Mitglied Werden",
        contactPageTitle: "KONTAKT",
        contactPageSubtitle: "Zögern Sie nicht, uns zu kontaktieren.",
        contactInfoTitle: "Kontaktinformationen",
        contactEmailLabel: "E-Mail",
        contactPhoneLabel: "Telefon",
        contactAddressLabel: "Adresse",
        contactAddress: "Mansuroğlu Mah. 283/1 Sk. Nr:2 GSK Plaza Etage:1 Whg:201 Bayraklı/Izmir",
        contactFormTitle: "Nachricht senden",
        contactFormName: "Vollständiger Name",
        contactFormEmail: "E-Mail",
        contactFormPhone: "Telefon",
        contactFormMessage: "Ihre Nachricht",
        contactFormSubmit: "Nachricht senden",
        contactFormSuccess: "Ihre Nachricht wurde erfolgreich gesendet!",
        contactFormError: "Ein Fehler ist aufgetreten, bitte versuchen Sie es erneut.",
        registerTitle: "Registrieren",
        registerPlaceholderFirstName: "Vorname",
        registerPlaceholderLastName: "Nachname",
        registerPlaceholderPhone: "Telefon",
        registerPlaceholderAddress: "Adresse",
        registerPlaceholderEmail: "E-Mail",
        registerPlaceholderPassword: "Passwort",
        registerErrorApproval: "Ihr Konto wartet auf die Genehmigung des Administrators.",
        registerErrorGeneral: "Registrierung fehlgeschlagen. Bitte überprüfen Sie Ihre Angaben.",
        registerButton: "Registrieren",
        registerWarning: "Achtung!",
        forgotTitle: "Passwort vergessen",
        forgotPlaceholderEmail: "Ihre E-Mail-Adresse",
        forgotSending: "Wird gesendet...",
        forgotButton: "Link zum Zurücksetzen des Passworts senden",
        forgotError: "Ein Fehler ist aufgetreten. Bitte überprüfen Sie Ihre E-Mail-Adresse.",
        forgotSuccess: "Ein Link zum Zurücksetzen des Passworts wurde an Ihre E-Mail-Adresse gesendet. Bitte überprüfen Sie Ihren Posteingang.",
        loginTitle: "Anmelden",
        loginEmail: "E-Mail",
        loginPassword: "Passwort",
        loginErrorApprove: "Ihr Konto wurde noch nicht genehmigt. Bitte warten Sie auf die Genehmigung durch den Administrator.",
        loginErrorNotFound: "Benutzerdaten nicht gefunden.",
        loginErrorFailed: "Anmeldung fehlgeschlagen. Bitte überprüfen Sie Ihre Eingaben.",
        loginButton: "Anmelden",
        loginRegister: "Registrieren",
        loginForgotPassword: "Passwort vergessen",
        loginLoading: "Lädt...",
        "videoPlaceholder": "Ihr Browser unterstützt das Video-Tag nicht.",
        "ulusalBarter": "ULUSAL BARTER",
        "mainHeading1": "Barter-Investitionssicherheit:",
        "mainHeading2": "Nationale Stärke, lokale Lösung!",
        "subtitle": "Ulusal Barter GmbH",
        "subtitleHighlight": "Jenseits von Bargeld",
        "subtitleDesc": "Ein starkes Fundament für bargeldlosen Handel mit unserem innovativen Barter-Investitionssystem",
        "subtitleQuote": "Wir gestalten nicht nur Ihr Heute, sondern auch Ihr Morgen gemeinsam",
        "discoverBarter": "Barter-System entdecken",
        "promoVideoTitle": "Ulusal Barter GmbH Werbevideo",
        "promoParagraph": "Als führende Barter-Plattform der Türkei stellen wir die wertschöpfenden Aspekte von Unternehmen in den Vordergrund und ermöglichen ihnen Wachstum ohne Liquiditätsengpässe. Ulusal Barter GmbH bietet Lösungen, die über traditionelle Finanzsysteme hinausgehen.",
        "barterBenefits": "Ihre Vorteile mit Barter",
        "barterBenefitsDesc": "Entdecken Sie die Möglichkeiten des bargeldlosen Handels.",
        "cashFlow": "Cashflow",
        "cashFlowDesc": "Reduzieren Sie den Bargeldabfluss und erhalten Sie Ihre Liquidität.",
        "stockManagement": "Lagerverwaltung",
        "stockManagementDesc": "Nutzen Sie Ihre Bestände im Austausch gegen Wert.",
        "marketAccess": "Marktzugang",
        "marketAccessDesc": "Gewinnen Sie neue Geschäftskontakte und Kunden.",
        "secureTrade": "Sicherer Handel",
        "secureTradeDesc": "Transparente und sichere Barter-Transaktionen.",
        "flexibleSolutions": "Flexible Lösungen",
        "flexibleSolutionsDesc": "Vielfältige Zahlungs- und Tauschmöglichkeiten.",
        "economicPower": "Wirtschaftliche Stärke",
        "economicPowerDesc": "Krisenresistenter Handel.",
        "learnMore": "Mehr erfahren",
        "latestListings": "Neueste Anzeigen",
        "joinAndSeeAll": "Mitglied werden und alles sehen",
        "whyChooseUs": "Warum uns wählen?",
        "reason1": "Wachstumschance ohne Barausgaben",
        "reason2": "System, das Lagerbestände in Wert umwandelt",
        "reason3": "Starkes Handelsnetzwerk in der ganzen Türkei",
        "reason4": "Transparente, registrierte und sichere Transaktionen",
        "reason5": "Individuelle Lösungen für jede Branche",
        "reason6": "Krisensicheres Handelsmodell",
        "futureMessage": "Gestalten Sie die Zukunft Ihres Handels heute mit Ulusal Barter GmbH.",
        "quote": "Entdecken Sie die Kraft des bargeldlosen Handels und entfalten Sie das Potenzial Ihres Unternehmens. ULUSAL BARTER GMBH — Ein wirtschaftliches Modell, das auf Wert statt Geld basiert.",
        "contactUs": "Kontaktieren Sie uns",
        "contactTitle": "Kontaktieren Sie uns",
        "companySlogan": "Barter-Investitionssicherheit: Nationale Stärke, lokale Lösung!",
        "links": "Links",
        "aboutUs": "Über uns",
        "barterSystem": "Barter-System",
        "membership": "Mitgliedschaft",
        "contact": "Kontakt",
        "address": "Adresse",
        "addressDetail": "Mansuroğlu Mah. 283/1 Str. Nr:2 GSK Plaza Etage:1 Whg:201 Bayraklı/İzmir",
        "phone": "0232 600 25 25",
        "email": "ulusalbarter@gmail.com",
        "copyright": "Alle Rechte vorbehalten.",
        "privacyPolicy": "Datenschutzrichtlinie",
        "cookies": "Cookies",
        "terms": "Bedingungen",
        "confirmMarkAsSold": "Möchten Sie diese Anzeige als 'verkauft' markieren?",
        "confirmMarkAsUnsold": "Möchten Sie diese Anzeige wieder als 'nicht verkauft' markieren?",
        "deleteConfirm": "Sind Sie sicher, dass Sie dieses Produkt löschen möchten?",
        "successOffer": "Angebot erfolgreich abgegeben.",
        "errorOffer": "Ein Fehler ist aufgetreten.",
        "invalidAmount": "Bitte geben Sie einen gültigen Betrag ein.",
        "withdrawSuccess": "Angebot wurde zurückgezogen.",
        "withdrawError": "Fehler beim Zurückziehen des Angebots.",
        "offerNotFound": "Kein Angebot zum Löschen gefunden.",
        "deleteSuccess": "Produkt wurde gelöscht.",
        "deleteError": "Fehler beim Löschen des Produkts.",
        "unknownUser": "Unbekannter Benutzer",
        "loading": "Wird geladen...",
        "giveOffer": "Angebot machen",
        "enterAmount": "Betrag eingeben",
        "cancel": "Abbrechen",
        "submit": "Senden",
        "listingNumber": "Anzeigenummer",
        "price": "Preis",
        "otherMedia": "Weitere Medien",
        "productDetails": "Produktdetails",
        "noDescription": "Keine Beschreibung vorhanden.",
        "edit": "Bearbeiten",
        "delete": "Löschen",
        "markAsSold": "Als verkauft markieren",
        "unmarkSold": "Verkauft-Markierung entfernen",
        "giveOfferButton": "Angebot machen",
        "withdrawOffer": "Angebot zurückziehen",
        "addFavorite": "Zu Favoriten hinzufügen",
        "removeFavorite": "Aus Favoriten entfernen",
        "fetchUsersError": "Fehler beim Abrufen der Benutzer.",
        "enterBalance": "Bitte geben Sie einen Guthabenbetrag ein.",
        "invalidBalance": "Bitte geben Sie einen gültigen Guthabenbetrag ein.",
        "enterDescription": "Bitte geben Sie eine Beschreibung ein.",
        "balanceAdded": "Guthaben erfolgreich hinzugefügt.",
        "balanceSubtracted": "Guthaben erfolgreich abgezogen.",
        "insufficientBalance": "Unzureichendes Guthaben.",
        "errorOccurred": "Ein Fehler ist aufgetreten.",
        "userBalances": "Benutzer-Guthaben",
        "noUsersWithRole": "Keine Benutzer mit Rolle 'user' gefunden.",
        "nameBalance": "Name / Guthaben",
        "amount": "Betrag",
        "action": "Aktion",
        "enterAmount": "Betrag eingeben",
        "enterDescription": "Beschreibung eingeben",
        "add": "Hinzufügen",
        "subtract": "Abziehen",
        "history": "Verlauf",
        "transactionHistory": "Transaktionsverlauf",
        "noHistory": "Kein Verlauf gefunden.",
        "addTransaction": "Hinzufügen",
        "subtractTransaction": "Abziehen",
        "pendingRequests": "Ausstehende Anfragen",
        "noPendingRequests": "Keine ausstehenden Benutzer.",
        "approve": "Genehmigen",
        "offers": "Angebote",
        "noOffersYet": "Noch keine Angebote.",
        "offerBy": "Angeboten von",
        "close": "Schließen",
        "Arsa": "Grundstück",
        "Arazi": "Land",
        "Otel": "Hotel",
        "Hizmet": "Dienstleistung",
        "Çiftlik": "Bauernhof",
        "Daire": "Wohnung",
        "Villa": "Villa",
        "Santral": "Kraftwerk",
        "Restaurant": "Restaurant",
        "Bahçe": "Garten",
        "Tarla": "Acker",
        "Parsel": "Parzelle",
        "Tesis": "Anlage",
        "Zeytinlik": "Olivenhain",
        "Fabrika": "Fabrik",
        "Beyaz Eşya": "Weiße Ware",
        "Ofis": "Büro",
        "Ev": "Haus",
        "Malikane": "Anwesen",
        "Tatil Köyü": "Ferienanlage",
        "Taksi": "Taxi",
        "Tekstil": "Textil",
        "Peyzaj": "Landschaft",
        "Sera": "Gewächshaus",
        "Estetik": "Ästhetik",
        "welcome": "Willkommen",
        "productsListed": "Produkte aufgelistet",
        "barterBalance": "Tauschguthaben",
        "accountHistory": "Kontoverlauf",
        "myFavorites": "Meine Favoriten",
        "myFavoriteListings": "Meine Lieblingsanzeigen",
        "noNameListing": "Unbenannte Anzeige",
        "close": "Schließen",
        "noFavoritesFound": "Keine Favoriten gefunden.",
        "balanceTracking": "Guthabenüberwachung",
        "addProduct": "Produkt hinzufügen",
        "viewRequests": "Anfragen anzeigen",
        "offers": "Angebote",
        "filter": "Filter",
        "logout": "Abmelden",
        "noResults": "Keine Ergebnisse gefunden",
        "noMatchingProducts": "Keine Produkte entsprechen den Filterkriterien.",
        "clearFilters": "Filter zurücksetzen",
        "barterCompleted": "TAUSCH ABGESCHLOSSEN",
        "productPinned": "Produkt wurde angeheftet.",
        "productUnpinned": "Produkt wurde gelöst.",
        "pinToTop": "Oben anheften",
        "unpin": "Von oben lösen",
        "details": "Details",
        "heroTitlePrefix": "Tauschsystem:",
        "heroTitleSuffix": "Die Zukunft Ihres Unternehmens",
        "heroDescription": "Entdecken Sie die Vorteile des bargeldlosen, wertorientierten Handels mit Ulusal Barter AG.",
        "videoFallback": "Ihr Browser unterstützt das Video-Tag nicht.",
        "whatIsBarterTitle": "Was ist Barter und wie funktioniert es?",
        "whatIsBarterDescription": "Lernen Sie ein einfaches, sicheres und innovatives Handelsmodell kennen.",
        "barterParagraph1": "Barter“ ist der direkte Tausch von Waren und Dienstleistungen ohne den Einsatz von Bargeld. Wir bei Ulusal Barter A.Ş. haben diese traditionelle Handelsform modernisiert, damit Unternehmen neue Märkte erschließen, ungenutzte Kapazitäten verwerten und ihren Cashflow optimieren können.",
        "barterParagraph2": "Unser System basiert auf einem Barter-Scheck- oder Punktesystem. Unsere Mitglieder erhalten anstelle von Bargeld sogenannte „Barter-Schecks“ für ihre verkauften Waren oder Dienstleistungen und können diese Schecks nutzen, um von anderen Mitgliedern benötigte Produkte oder Leistungen zu erwerben. So bewahren Unternehmen ihre Liquidität und steigern ihren Wert.",
        "barterParagraph3": "Das Expertenteam von Ulusal Barter A.Ş. begleitet Sie durch alle Handelsprozesse und bietet Ihnen eine sichere und transparente Plattform.",
        "benefit1Title": "Werttausch",
        "benefit1Desc": "Tauschen Sie Ihre Produkte und Dienstleistungen ohne Bargeld.",
        "benefit2Title": "Bargeldschutz",
        "benefit2Desc": "Erhöhen Sie die Liquidität Ihres Unternehmens.",
        "benefit3Title": "Weitreichendes Netzwerk",
        "benefit3Desc": "Zugang zu Tausenden von Unternehmen.",
        "benefit4Title": "Sichere Transaktionen",
        "benefit4Desc": "Alle Transaktionen sind abgesichert.",
        "barterStepsTitle": "Barter-Prozess: Einfache und schnelle Schritte",
        "barterStepsDesc": "So einfach ist der Tausch mit Ulusal Barter AG!",
        "step1Title": "Mitgliedschaft und Definition",
        "step1Desc": "Registrieren Sie Ihr Unternehmen, definieren Sie Ihre Produkte und Dienstleistungen...",
        "step2Title": "Handel und Scheck-Verdienst",
        "step2Desc": "Verkaufen Sie Ihre definierten Produkte, verdienen Sie Barter-Schecks.",
        "step3Title": "Bedürfnisse decken",
        "step3Desc": "Nutzen Sie Barter-Schecks, um benötigte Produkte und Dienstleistungen zu erhalten.",
        "step4Title": "Wachstum und Gewinn",
        "step4Desc": "Nutzen Sie ungenutzte Kapazitäten und genießen Sie finanzielle Flexibilität.",
        "faqTitle": "Häufig gestellte Fragen",
        "faqDescription": "Was Sie über das Barter-System wissen möchten.",
        "faq1Q": "Was ist das Barter-System?",
        "faq1A": "Barter ist eine Handelsmethode, bei der Waren und Dienstleistungen direkt ohne den Einsatz von Geld getauscht werden. Im System von Ulusal Barter AG erhalten Mitglieder Barter-Schecks, die sie für ihre Bedürfnisse bei anderen Mitgliedern einsetzen können.",
        "faq2Q": "Wer kann Barter nutzen?",
        "faq2A": "Unternehmen jeder Branche und Größe können dem Barter-System beitreten. Besonders für Unternehmen mit ungenutzten Lagerbeständen bietet es große Vorteile. Unser System verfügt über ein umfangreiches Mitgliedsnetzwerk.",
        "faq3Q": "Wie werden Barter-Schecks verwendet?",
        "faq3A": "Die verdienten Barter-Schecks können für alle auf der Plattform von Ulusal Barter AG gelisteten Produkte und Dienstleistungen verwendet werden. Sie gelten wie Bargeld und sind für alle Transaktionen im System gültig.",
        "faq4Q": "Ist es sicher?",
        "faq4A": "Ja, bei Ulusal Barter AG legen wir großen Wert auf Transparenz und Sicherheit bei allen Transaktionen. Jede Transaktion wird protokolliert und bei Streitigkeiten erhalten Sie professionelle Unterstützung.",
        "faq5Q": "Welche Vorteile bietet das Barter-System meinem Unternehmen?",
        "faq5A": "Es bietet viele Vorteile wie optimierten Cashflow, Nutzung ungenutzter Bestände, Zugang zu neuen Kunden, Steigerung des Marktanteils und Widerstandsfähigkeit gegenüber wirtschaftlichen Schwankungen.",
        "ctaTitle": "Treten Sie der Barter-Welt bei!",
        "ctaDescription": "Verwandeln Sie die Zukunft Ihres Unternehmens und profitieren Sie von den Vorteilen des bargeldlosen Handels. Kontaktieren Sie uns noch heute.",
        "ctaButton": "Jetzt Mitglied werden",
        "filterLocation": "Standort suchen",
  "searchPlaceholder": "Stadt, Region, Bezirk...",
  "type": "Typ",
  "saleStatus": "Verkaufsstatus",
  "all": "Alle",
  "unsold": "Nicht verkauft",
  "sold": "Verkauft",
    },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [currentLocale, setCurrentLocale] = useState(defaultLocale);

    useEffect(() => {
        const stored = localStorage.getItem('languageCode');
        if (stored && ['tr', 'en', 'de'].includes(stored)) {
            setCurrentLocale(stored);
        }
    }, []);

    const changeLanguage = (lang) => {
        setCurrentLocale(lang);
        localStorage.setItem('languageCode', lang);
    };

    const translate = (key) => {
        return localizedStrings[currentLocale]?.[key] || key;
    };

    const getProductTypes = () => {
        return localizedStrings[currentLocale]?.productTypes || [];
    };

    return (
        <LanguageContext.Provider
            value={{
                currentLocale,
                changeLanguage,
                translate,
                getProductTypes,
            }}
        >
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
